package utils;

public class Constant {

    public static final String OBJECT_ACCOUNT_REQUIRED = "THE OBJECT ACCOUNT IS REQUIRED";

    public static final String OBJECT_PAYMENT_REQUIRED = "THE OBJECT PAYMENT IS REQUIRED";
    public static final String ACCOUNT_NUMBER_EMPTY = "THE ACCOUNT NUMBER CANNOT BE EMPTY";
    public static final String ACCOUNT_NUMBER_REQUIRED = "THE ACCOUNT NUMBER IS REQUIRED";
    public static final String BALANCE_REQUIRED = "THE BALANCE IS REQUIRED";
    public static final String BALANCE_NOT_NEGATIVE = "THE BALANCE CANNOT BE NEGATIVE";
    public static final String ACCOUNT_NUMBER_NOT_FOUND = "THE ACCOUNT NUMBER NOT FOUND";

    public static final String ACCOUNT_ORIGIN_EMPTY = "THE ACCOUNT NUMBER ORIGIN CANNOT BE EMPTY";
    public static final String ACCOUNT_ORIGIN_REQUIRED = "THE ACCOUNT NUMBER ORIGIN IS REQUIRED";

    public static final String ACCOUNT_DESTINATION_EMPTY = "THE ACCOUNT NUMBER DESTINATION CANNOT BE EMPTY";
    public static final String ACCOUNT_DESTINATION_REQUIRED = "THE ACCOUNT NUMBER DESTINATION IS REQUIRED";

    public static final String ACCOUNT_ORIGIN_NOT_REGISTERED = "THE ACCOUNT ORIGIN NOT REGISTERED";
    public static final String ACCOUNT_DESTINATION_NOT_REGISTERED = "THE ACCOUNT DESTINATION NOT REGISTERED";
}
